//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackSlipApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatch_Code
    {
        public int ID { get; set; }
        public string PartNum { get; set; }
        public string Part_Desc { get; set; }
        public string FDA_Product_Code { get; set; }
        public string Industry___Product_Code { get; set; }
        public Nullable<decimal> Tariff { get; set; }
        public string FDA_Classification { get; set; }
        public Nullable<decimal> US_HTS { get; set; }
        public string Invoice_Description { get; set; }
        public string Methodology { get; set; }
        public string Notes_Questions { get; set; }
    }
}
