//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackSlipApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatch_PackingDetails
    {
        public int ID { get; set; }
        public int PackslipNo { get; set; }
        public Nullable<int> InvoiceNo { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
