//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackSlipApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatch_PackslipNum
    {
        public int ID { get; set; }
        public Nullable<int> Packslip_No { get; set; }
        public Nullable<int> Invoice_No { get; set; }
    }
}
