//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackSlipApp.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchData
    {
        public int P_ID { get; set; }
        public int ID { get; set; }
        public int Packslip_No { get; set; }
        public int Invoice_No { get; set; }
        public string PartNo { get; set; }
        public string PoNo { get; set; }
        public Nullable<int> LineNo { get; set; }
        public string JobNo { get; set; }
        public Nullable<bool> LM { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> w_pcs { get; set; }
        public Nullable<int> Box { get; set; }
        public string Material_Details { get; set; }
        public Nullable<decimal> total_weight { get; set; }
        public string packing_type { get; set; }
        public Nullable<decimal> Box_weight { get; set; }
        public Nullable<bool> supervisor_approval { get; set; }
        public Nullable<bool> purchaser_verification { get; set; }
        public Nullable<bool> finance_approval { get; set; }
    }
}
