//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackSlipApp.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dispatch_Staticdata
    {
        public int ID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string PackSlipNo { get; set; }
        public Nullable<System.DateTime> PackSlipDate { get; set; }
        public string PortOfLoading { get; set; }
        public string PortOfDischarge { get; set; }
        public string CountryOfOrigin { get; set; }
        public string PaymentTerms { get; set; }
        public string Vessel_FlightNo { get; set; }
        public string FinalDestination { get; set; }
        public string DestinationCountry { get; set; }
        public string TermsOfDelivery { get; set; }
        public string CIN { get; set; }
        public string IECNO { get; set; }
        public string GSTIN { get; set; }
        public string FEI { get; set; }
        public string FDAFacilityRegn { get; set; }
        public string SNPlantAdd { get; set; }
        public string ConsigneeAdd { get; set; }
        public string BuyerAdd { get; set; }
    }
}
