//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackSlipApp.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dispatch_Staticdata
    {
        public int ID { get; set; }
        public string SNAddLine1 { get; set; }
        public string SNAddLine2 { get; set; }
        public string SNAddLine3 { get; set; }
        public string SNAddLine4 { get; set; }
        public string SNAddLine5 { get; set; }
        public string SNAddLine6 { get; set; }
        public string SNAddLine7 { get; set; }
        public string PortOfLoading { get; set; }
        public string CountryOfOrigin { get; set; }
        public string PaymentTerms { get; set; }
        public string Vessel_FlightNo { get; set; }
        public string TermsOfDelivery { get; set; }
        public string IECNO { get; set; }
        public string GSTIN { get; set; }
        public string FEI_ { get; set; }
        public string FDAFacilityRegn_ { get; set; }
        public string CIN { get; set; }
        public string Signature { get; set; }
    }
}
