//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackSlipApp.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatch_Grade
    {
        public int ID { get; set; }
        public Nullable<int> InputSerialNumber { get; set; }
        public string Material_Type { get; set; }
        public string Grade { get; set; }
    }
}
