//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackSlipApp.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dispatch_type
    {
        public int id { get; set; }
        public string type { get; set; }
        public string OurAddressName { get; set; }
        public string OurPlantAddressLine1 { get; set; }
        public string OurPlantAddressLine2 { get; set; }
        public string OurPlantAddressLine3 { get; set; }
        public string Dist { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<int> Phone { get; set; }
        public string ConsigneeAddressName { get; set; }
        public string ConsigneeAddressLine1 { get; set; }
        public string ConsigneeAddressLine2 { get; set; }
        public string ConsigneeAddressLine3 { get; set; }
        public string ConsigneeDist { get; set; }
        public string ConsigneeState { get; set; }
        public string ConsigneeCountry { get; set; }
        public string ConsigneeFacility { get; set; }
        public Nullable<int> ConsigneePhone { get; set; }
        public string BuyerAddressName { get; set; }
        public string BuyerAddressLine1 { get; set; }
        public string BuyerAddressLine2 { get; set; }
        public string BuyerAddressLine3 { get; set; }
        public string BuyerDist { get; set; }
        public string BuyerState { get; set; }
        public string BuyerFacility { get; set; }
        public string BuyerCountry { get; set; }
        public Nullable<int> BuyerPhone { get; set; }
    }
}
