//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackSlipApp.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatch_Data
    {
        public int ID { get; set; }
        public int PID { get; set; }
        public string PackslipNo { get; set; }
        public string InvoiceNo { get; set; }
        public string PartNo { get; set; }
        public string PoNo { get; set; }
        public Nullable<int> LineNo { get; set; }
        public string JobNo { get; set; }
        public Nullable<bool> LM { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> wPcs { get; set; }
        public Nullable<int> Box { get; set; }
        public string MaterialDetails { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public string PackingType { get; set; }
        public Nullable<decimal> BoxWeight { get; set; }
        public Nullable<bool> SupervisorApproval { get; set; }
        public Nullable<bool> PurchaserVerification { get; set; }
        public Nullable<bool> FinanceApproval { get; set; }
        public string PartDesc { get; set; }
        public Nullable<int> BoxSize { get; set; }
    }
}
