//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackSlipApp.Database.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITe_INDIAEntities1 : DbContext
    {
        public ITe_INDIAEntities1()
            : base("name=ITe_INDIAEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dispatch_PackingDetails> Dispatch_PackingDetails { get; set; }
        public virtual DbSet<DispatchData> DispatchDatas { get; set; }
        public virtual DbSet<Dispatch_Code> Dispatch_Code { get; set; }
        public virtual DbSet<Dispatch_Grade> Dispatch_Grade { get; set; }
    }
}
